language: python
matrix:
  include:
  - python: "3.6"
    env: TOXENV=py36
install:
  - pip install tox
  - pip install mock
script:
  - tox
deploy:
  provider: pypi
  user: Mahmoud.Abdelkader
  password:
    secure: OhjlsFN3zIHqW6PlpSanlHhJ3Bx6jIAPZM6jObMeA4yXp74NCdzpPBS/Drdj0dnKXj5edkzUQ4iC72Eyx5vmHvq0yHIM49FvfEliJ5oihQGgqZufqA6EjaVSvRaRh7ZERcwGKzbPpCGulh55V1bURDFOTXwk2n9X4/xmIyX3v7w=
  on:
    tags: true
    all_branches: true
    repo: mahmoudimus/clubhouse
